f = open('app.html', 'rb')
data = f.read()
f.close()
data = data.replace(b'\xc2\x8f\xc2\x8f Disconnect', b'\xe2\x8f\xbb Disconnect')
data = data.replace(b'Start saving \xc3\xa2\xe2\x80\xa0\xe2\x80\x99', b'Start saving \xe2\x86\x92')
data = data.replace(b'Start Saving \xc3\xa2\xe2\x80\xa0\xe2\x80\x99', b'Start Saving \xe2\x86\x92')
f = open('app.html', 'wb')
f.write(data)
f.close()
print('Fixed!')
